language: node_js

node_js:
- "10"

cache:
  directories:
    - node_modules

# 알림 설정  
# notifications:
#   email:
#     recipients:
#       - hkroh.nonoll@gmail.com
#     on_success: always
#     on_failure: always

# Job Lifecycle
# 1.  OPTIONAL Install apt addons
# 2.  OPTIONAL Install cache components
# 3.  before_install
# 4.  install
# 5.  before_script
# 6.  script
# 7.  OPTIONAL before_cache (for cleaning up cache)
# 8.  after_success or after_failure
# 9.  OPTIONAL before_deploy
# 10. OPTIONAL deploy
# 11. OPTIONAL after_deploy
# 12. after_script
# see: https://docs.travis-ci.com/user/job-lifecycle/#the-job-lifecycle


install:
  - npm install


before_install:
  - npm install -g gatsby-cli


script:
  - gatsby build --prefix-paths


# 배포 설정
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: public
  target_branch: master
  skip_cleanup: true
  keep_history: true
  on:
    branch: gatsby