language: node_js

node_js:
- "10"

cache:
  directories:
    - node_modules

# 알림 설정  
# notifications:
#   email:
#     recipients:
#       - hkroh.nonoll@gmail.com
#     on_success: always
#     on_failure: always

# 배포 설정
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master

before_install:
  - npm install -g gatsby-cli

install:
  - npm install

script:
  - gatsby build --prefix-paths
  - npm run deploy