language: node_js

before_script:
  - npm install -g gatsby-cli
  - npm install -g yarn

node_js:
  - "10"

install:
  - yarn install


before_script:
  - git config --global user.name 'hkroh.nonoll'
  - git config --global user.email 'hkroh.nonoll@gmail.com'

script:
  - gatsby build --prefix-paths

# 알림 설정  
# notifications:
#   email:
#     recipients:
#       - hkroh.nonoll@gmail.com
#     on_success: always
#     on_failure: always

# 배포 설정
deploy:
  github-token: $GITHUB_TOKEN
  provider: script
  # Note: change "docs" to the directory where your gatsby-site lives, if necessary
  script: cd public/ && yarn install && yarn run deploy
  skip_cleanup: true
  on:
    branch: master
