language: node_js

node_js:
- "10"

cache:
  directories:
    - node_modules

# 알림 설정  
# notifications:
#   email:
#     recipients:
#       - hkroh.nonoll@gmail.com
#     on_success: always
#     on_failure: always

# 배포 설정
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  token: $GITHUB_TOKEN
  keep_history: true
  local_dir: public
  target_branch: master
  on:
    branch: gatsby

before_install:
  - npm install -g gatsby-cli

install:
  - npm install

script:
  - gatsby build --prefix-paths