language: node_js

before_script:
  - npm install -g gatsby-cli

node_js:
  - "10"

# 알림 설정  
# notifications:
#   email:
#     recipients:
#       - hkroh.nonoll@gmail.com
#     on_success: always
#     on_failure: always


# job-lifecycle: https://docs.travis-ci.com/user/job-lifecycle/
before_script:
  - git config --global user.name 'hkroh.nonoll'
  - git config --global user.email 'hkroh.nonoll@gmail.com'

install:
  - npm install

script:
  - gatsby build --prefix-paths
  - npm run deploy

# 배포 설정
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
